//
//  DetailsWorkerTests.swift
//  pokemon-ios
//
//  Created by Matías Elorriaga on 8/4/17.
//  Copyright (c) 2017 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import pokemon_ios
import XCTest

class DetailsWorkerTests: XCTestCase {
    
    // MARK: - Subject under test
    
    var sut: DetailsWorker!
    
    // MARK: - Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupDetailsWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: - Test setup
    
    func setupDetailsWorker() {
//        sut = DetailsWorker()
    }
    
    // MARK: - Test doubles
    
    // MARK: - Tests
    
    func testSomething() {
        // Given
        
        // When
        
        // Then
    }
    
}
