//
//  DetailsWorkerTests.swift
//  pokemon-ios
//
//  Created by Matías Elorriaga on 8/4/17.
//  Copyright (c) 2017 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import pokemon_ios
import XCTest

class DetailsWorkerTests: XCTestCase {
    
    var sut: DetailsWorker!
    
    override func setUp() {
        super.setUp()
        setupDetailsWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // setup
    
    func setupDetailsWorker() {
//        sut = DetailsWorker()
    }
    
    // test doubles
    
    // tests
    
    func testSomething() {
        // given
        
        // when
        
        // then
    }
    
}
