//
//  DetailsInteractorTests.swift
//  pokemon-ios
//
//  Created by Matías Elorriaga on 8/4/17.
//  Copyright (c) 2017 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import pokemon_ios
import XCTest

class DetailsInteractorTests: XCTestCase {
    
    // MARK: - Subject under test
    
    var sut: DetailsInteractor!
    
    // MARK: - Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupDetailsInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: - Test setup
    
    func setupDetailsInteractor() {
        sut = DetailsInteractor()
    }
    
    // MARK: - Test doubles
    
    // MARK: - Tests
    
    func testSomething() {
        // Given
        
        // When
        
        // Then
    }
    
}
