//
//  DetailsWorkerTests.swift
//  pokemon-ios
//
//  Created by Matías Elorriaga on 8/4/17.
//  Copyright (c) 2017 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import pokemon_ios
import XCTest

class DetailsWorkerTests: XCTestCase {
    
    var sut: DetailsWorker!
    
    override func setUp() {
        super.setUp()
        setupDetailsWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // setup
    
    func setupDetailsWorker() {
        sut = DetailsWorker(detailsStore: DetailsStoreSpy())
    }
    
    // test doubles
    
    class DetailsStoreSpy: DetailsStore {
        
        var getPokemonDetailsCalled = false
        var id: Int!
        
        func getPokemonDetails(id: Int, completionHandler: @escaping (Pokemon?) -> Void) {
            getPokemonDetailsCalled = true
            self.id = id
            completionHandler(nil)
        }
        
    }
    
    // tests
    
    func testShouldCallStore() {
        // given
        let detailsStoreSpy = DetailsStoreSpy()
        sut.detailsStore = detailsStoreSpy
        
        // when
        sut.getPokemonDetails(id: 25) { _ in }
        
        // then
        XCTAssert(detailsStoreSpy.getPokemonDetailsCalled)
    }
    
}
