//
//  MainWorkerTests.swift
//  pokemon-ios
//
//  Created by Matías Elorriaga on 8/4/17.
//  Copyright (c) 2017 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import pokemon_ios
import XCTest

class MainWorkerTests: XCTestCase {
    
    var sut: MainWorker!
    
    override func setUp() {
        super.setUp()
        setupMainWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // setup
    
    func setupMainWorker() {
        sut = MainWorker(mainStore: MainStoreProtocolSpy())
    }
    
    // test doubles
    
    class MainStoreProtocolSpy: MainStoreProtocol {
        
        var getPokemonListCalled = false
        
        func getPokemonList(completionHandler: @escaping (APIResourceList?) -> Void) {
            getPokemonListCalled = true
            completionHandler(nil)
        }
        
    }
    
    // tests
    
    func testShouldCallStore() {
        // given
        let mainStoreProtocolSpy = MainStoreProtocolSpy()
        sut.mainStore = mainStoreProtocolSpy
        
        // when
        sut.getPokemonList { _ in }

        // then
        XCTAssert(mainStoreProtocolSpy.getPokemonListCalled)
    }
    
}
