//
//  MainWorker.swift
//  pokemon-ios
//
//  Created by Matías Elorriaga on 4/4/17.
//  Copyright (c) 2017 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Foundation

protocol MainStoreProtocol {
    func getPokemonList(completionHandler: @escaping (APIResourceList?) -> Void)
}

class MainWorker {
    
    var mainStore: MainStoreProtocol
    
    init(mainStore: MainStoreProtocol) {
        self.mainStore = mainStore
    }
    
    func getPokemonList(completionHandler: @escaping (APIResourceList?) -> Void) {
        mainStore.getPokemonList { apiResourceList in
            completionHandler(apiResourceList)
        }
    }
    
}
