//
//  MainWorker.swift
//  pokemon-ios
//
//  Created by Matías Elorriaga on 4/4/17.
//  Copyright (c) 2017 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Alamofire
import AlamofireObjectMapper

class MainWorker {
    
    func getPokemonList(completionHandler: @escaping (APIResourceList?) -> Void) {
        let url = "http://pokeapi.co/api/v2/pokemon/"
        let parameters = ["limit": 150]
        
        Alamofire.request(url, parameters: parameters).responseObject { (response: DataResponse<APIResourceList>) in
            completionHandler(response.result.value)
        }
    }
    
}
