//
//  MainInteractor.swift
//  pokemon-ios
//
//  Created by Matías Elorriaga on 4/4/17.
//  Copyright (c) 2017 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Foundation

protocol MainInteractorInput {
    func doGetPokemonList(request: Main.GetPokemonList.Request)
}

protocol MainInteractorOutput {
    func presentGetPokemonList(response: Main.GetPokemonList.Response)
}

class MainInteractor: MainInteractorInput {
    
    var output: MainInteractorOutput!
    var worker = MainWorker(mainStore: MainAPIStore())
    
    func doGetPokemonList(request: Main.GetPokemonList.Request) {
        worker.getPokemonList { apiResourceList in
            let response = Main.GetPokemonList.Response(apiResourceList: apiResourceList)
            self.output.presentGetPokemonList(response: response)
        }
    }
    
}
