//
//  MainRouter.swift
//  pokemon-ios
//
//  Created by Matías Elorriaga on 4/4/17.
//  Copyright (c) 2017 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MainRouterInput {
    func navigateToDetailsScene()
}

class MainRouter: MainRouterInput {
    
    weak var viewController: MainViewController!
    
    // navigation
    
    func navigateToDetailsScene() {
        viewController.performSegue(withIdentifier: "FromMainToDetailsSegue", sender: nil)
    }
    
    // communication
    
    func passDataToNextScene(segue: UIStoryboardSegue) {
        if segue.identifier == "FromMainToDetailsSegue" {
            passDataToFromMainToSegueScene(segue: segue)
        }
    }
    
    private func passDataToFromMainToSegueScene(segue: UIStoryboardSegue) {
        if let selectedIndexPath = viewController.tableView.indexPathForSelectedRow {
            let pokemon = viewController.pokemonList[selectedIndexPath.row]
            let detailsViewController = segue.destination as! DetailsViewController
            
            detailsViewController.pokemonId = pokemon.id
            detailsViewController.pokemonName = pokemon.name
        }
    }
    
}
