//
//  MainPresenter.swift
//  pokemon-ios
//
//  Created by Matías Elorriaga on 4/4/17.
//  Copyright (c) 2017 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MainPresenterInput
{
    func presentSomething(response: Main.GetPokemonList.Response)
}

protocol MainPresenterOutput: class
{
    func showPokemonList(viewModel: Main.GetPokemonList.ViewModel)
}

class MainPresenter: MainPresenterInput {
    
    weak var output: MainPresenterOutput!
    
    func presentSomething(response: Main.GetPokemonList.Response) {
        if let results = response.apiResourceList?.results {
            let pokemonList = results.map({
                return Pokemon(JSON: [
                    "id": Int($0.url!.components(separatedBy: "/")[6])!,
                    "name": $0.name!
                ])!
            })
            let viewModel = Main.GetPokemonList.ViewModel(pokemonList: pokemonList)
            output.showPokemonList(viewModel: viewModel)
        } else {
            let viewModel = Main.GetPokemonList.ViewModel(pokemonList: [])
            output.showPokemonList(viewModel: viewModel)
        }
    }
    
}
