//
//  MainInteractor.swift
//  pokemon-ios
//
//  Created by Matías Elorriaga on 4/4/17.
//  Copyright (c) 2017 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MainInteractorInput
{
  func doSomething(request: Main.Something.Request)
}

protocol MainInteractorOutput
{
  func presentSomething(response: Main.Something.Response)
}

class MainInteractor: MainInteractorInput
{
  var output: MainInteractorOutput!
  var worker: MainWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: Main.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = MainWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = Main.Something.Response()
    output.presentSomething(response: response)
  }
}
