//
//  DetailsWorker.swift
//  pokemon-ios
//
//  Created by Matías Elorriaga on 5/4/17.
//  Copyright (c) 2017 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Foundation
import Alamofire
import AlamofireObjectMapper

protocol DetailsStore {
    func getPokemonDetails(id: Int, completionHandler: @escaping (Pokemon?) -> Void)
}

class DetailsWorker {
    
    var detailsStore: DetailsStore
    
    init(detailsStore: DetailsStore) {
        self.detailsStore = detailsStore
    }
    
    func getPokemonDetails(id: Int, completionHandler: @escaping (Pokemon?) -> Void) {
        detailsStore.getPokemonDetails(id: id) { pokemon in
            completionHandler(pokemon)
        }
    }
    
}
