//
//  DetailsInteractor.swift
//  pokemon-ios
//
//  Created by Matías Elorriaga on 5/4/17.
//  Copyright (c) 2017 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol DetailsInteractorInput {
    func doGetPokemonDetails(request: Details.GetPokemonDetails.Request)
}

protocol DetailsInteractorOutput {
    func presentGetPokemonDetails(response: Details.GetPokemonDetails.Response)
}

class DetailsInteractor: DetailsInteractorInput {
    
    var output: DetailsInteractorOutput!
    
    func doGetPokemonDetails(request: Details.GetPokemonDetails.Request) {
        DetailsWorker().getPokemonDetails(id: request.id) { pokemon in
            let response = Details.GetPokemonDetails.Response(pokemon: pokemon)
            self.output.presentGetPokemonDetails(response: response)
        }
    }
    
}
