//
//  DetailsWorker.swift
//  pokemon-ios
//
//  Created by Matías Elorriaga on 5/4/17.
//  Copyright (c) 2017 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Alamofire
import AlamofireObjectMapper

class DetailsWorker {
    
    func getPokemonDetails(id: Int, completionHandler: @escaping (Pokemon?) -> Void) {
        let url = "http://pokeapi.co/api/v2/pokemon/\(id)/"
        
        Alamofire.request(url).responseObject { (response: DataResponse<Pokemon>) in
            completionHandler(response.result.value)
        }
    }
    
}
