//
//  DetailsViewController.swift
//  pokemon-ios
//
//  Created by Matías Elorriaga on 5/4/17.
//  Copyright (c) 2017 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol DetailsViewControllerInput
{
    func displaySomething(viewModel: Details.Something.ViewModel)
}

protocol DetailsViewControllerOutput
{
    func doSomething(request: Details.Something.Request)
}

class DetailsViewController: UIViewController, DetailsViewControllerInput {
    
    var output: DetailsViewControllerOutput!
    var router: DetailsRouter!
    
    @IBOutlet weak var frontImageView: UIImageView!
    @IBOutlet weak var backImageView: UIImageView!
    @IBOutlet weak var idLabel: UILabel!
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var heightLabel: UILabel!
    @IBOutlet weak var weightLabel: UILabel!
    @IBOutlet weak var baseExperienceLabel: UILabel!
    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
    @IBOutlet var pokemonViewCollection: [UIView]!
    
    var pokemonId: Int?
    var pokemonName: String?
    
    override func awakeFromNib() {
        super.awakeFromNib()
        DetailsConfigurator.sharedInstance.configure(viewController: self)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        showLoadingScreen()
        
        doSomethingOnLoad()
    }
    
    private func showLoadingScreen() {
        pokemonViewCollection.forEach { $0.isHidden = true}
    }
    
    func doSomethingOnLoad() {
        let request = Details.Something.Request()
        output.doSomething(request: request)
    }
    
    func displaySomething(viewModel: Details.Something.ViewModel) {
        // nameTextField.text = viewModel.name
    }
    
}
